name = "OptimRegistry"
uuid = "01621ee8-d7a9-457d-8d43-bd9cf2ade94e"
repo = "https://github.com/GillesBareilles/OptimRegistry.jl"
description = "My private registry"

[packages]
57061203-8ea9-4995-b8fb-f2bb2c372b50 = { name = "PlotsOptim", path = "P/PlotsOptim" }
