name = "OptimRegistry"
uuid = "01621ee8-d7a9-457d-8d43-bd9cf2ade94e"
repo = "https://github.com/GillesBareilles/OptimRegistry.jl"
description = "My private registry"

[packages]
1f36449f-5f52-4ce1-8bf6-72aeff6ffb2f = { name = "EigenDerivatives", path = "E/EigenDerivatives" }
23bb58a7-9af7-4ddc-91d0-c8528a741764 = { name = "ConvexHullProjection", path = "C/ConvexHullProjection" }
410873c1-f8f8-46a6-bf19-1d1ac773cd81 = { name = "ConjugateGradient", path = "C/ConjugateGradient" }
4725afc4-59ac-4551-9f29-ef4e002d52ed = { name = "GlobalCompositeNewton", path = "G/GlobalCompositeNewton" }
5655f2e6-550e-45fb-8023-520ea411539c = { name = "NonSmoothProblems", path = "N/NonSmoothProblems" }
57061203-8ea9-4995-b8fb-f2bb2c372b50 = { name = "PlotsOptim", path = "P/PlotsOptim" }
85789b06-2fe2-4664-9b69-af753cb80372 = { name = "QuadProgSimplex", path = "Q/QuadProgSimplex" }
8d4dcc58-3161-4603-87cb-6c574b0842d7 = { name = "LocalCompositeNewton", path = "L/LocalCompositeNewton" }
b67afb87-58e8-4720-854f-53d482c26be0 = { name = "QuadProgSpectraplex", path = "Q/QuadProgSpectraplex" }
f37854fc-8eb2-424e-b8d4-38d006def410 = { name = "NonSmoothSolvers", path = "N/NonSmoothSolvers" }
